### ISSUE TITLE
Add new contact field

### ISSUE THREAD

**Issue by p3d2** [opieters/limecv#10]
I'm trying to insert the orcid info in my cv. How can we add a new field and a new icon to the contact info?
Thanks for the awesome template.
Pedro

**Comment by opieters** [comment]
Not possible at the moment. This is planned for the next release. If you really need it right now, you should modify the source code.

**Comment by opieters** [comment]
You can now add custom contact fields using the following macro:
`\cvContactTemplate[]{}{}` The optional argument is a link. For example, for ORCiD this can be: `\cvContactTemplate[https://orcid.org/]{\faGraduationCap}{ORCiD}`.

**Comment by opieters** [comment]
If you only use the CTAN version, you will have to wait for the next big release of limecv since I do not upload minor releases (for now).
