### ISSUE TITLE
cvSetLanguage{chinese} error

### ISSUE THREAD

**Issue by kongyanye** [opieters/limecv#15]
When using the command cvSetLanguage{chinese} and change the typesetting into xeletex, the code can be compiled without errors, but the output pdf is blank. And if use pdflatex and change to English, it works well. Can anyone help me with it?

**Comment by opieters** [comment]
Can you send me a copy of your tex-file?

**Comment by kongyanye** [comment]
I guess the problem is my software setting. When using in Miktex Windows, it gives error. But when I use the same code in overleaf it works well now. 

By the way, another problem I have is how to use the icons that are only available in fontawesome pro? If I have a pro account, how can I use the pro icons in overleaf? Thanks in advance.

**Comment by opieters** [comment]
Currently, the document class does not provide a means to update the section icons, but for hobbies etc it is possible I think. You should upload the OTF font files to your overleaf project and then declare a new font and use the UTF-8 codepoints like this: `\ProvideDocumentCommand{\faAddressCard}{}{{\cv@FA\symbol{"F2B9}}}`. `F2B9` is the hex code you can find on the fontawesome website. 

If you really want to use different icons for the different sections, I would currently try to redefine the commands used for those symbols. For that, you will need to look at the source code.

**Comment by kongyanye** [comment]
> Currently, the document class does not provide a means to update the section icons, but for hobbies etc it is possible I think. You should upload the OTF font files to your overleaf project and then declare a new font and use the UTF-8 codepoints like this: `\ProvideDocumentCommand{\faAddressCard}{}{{\cv@FA\symbol{"F2B9}}}`. `F2B9` is the hex code you can find on the fontawesome website.
> 
> If you really want to use different icons for the different sections, I would currently try to redefine the commands used for those symbols. For that, you will need to look at the source code.

Thanks for your comment. I think I've found what I need https://github.com/thinkparallel/faXeTeX/blob/master/fontawesome.pdf.
