### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by nevadarain** [opieters/limecv#17]
I am using TexStudio and Miktex and I can't seem to get this template to compile.  I getting a bunch of errors that seem to be centered around the Fira.  Where should I put the Fira folder or how do you install this font? The errors i receive are below.  Thank you.

line 198: Package fontspec Error: The font "FiraSans" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraSans" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraSans" cannot be found. \cv@loadFonts
line 198: Font \TU/FiraSans(0)/m/n/10=FiraSans:mode=node;+tlig; at 10pt not loadable: metric data not found or bad. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraSans" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraSans" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraSans" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraMono" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraMono" cannot be found. \cv@loadFonts
line 198: Package fontspec Error: The font "FiraMono" cannot be found. \cv@loadFonts
line 39: Font \TU/FiraSans(0)/m/n/17.28=FiraSans:mode=node;+tlig; at 17.28pt not loadable: metric data not found or bad. \cvID{John}{Doe}{picture}{position}
line 52: Font \TU/FiraMono(0)/m/n/10=FiraMono:mode=node; at 10pt not loadable: metric data not found or bad. ...se.io/johndoe}{\texttt{AAAA 5555 BBBB FFFF}}
line 66: Font \TU/FiraSans(0)/m/n/7=FiraSans:mode=node;+tlig; at 7pt not loadable: metric data not found or bad. \cvInterestsProfessional
line 66: Font \TU/FiraSans(0)/m/n/5=FiraSans:mode=node;+tlig; at 5pt not loadable: metric data not found or bad. \cvInterestsProfessional
line 66: Font \TU/FiraSans(0)/m/it/10=FiraSans:mode=node;+tlig; at 10pt not loadable: metric data not found or bad. \cvInterestsProfessional
line 79: Font \TU/FiraSans(0)/m/n/14.4=FiraSans:mode=node;+tlig; at 14.4pt not loadable: metric data not found or bad. \begin{cvEducation}
line 79: Font \TU/FiraSans(0)/bx/n/14.4=FiraSans:mode=node;+tlig; at 14.4pt not loadable: metric data not found or bad. \begin{cvEducation}
line 94: Font \TU/FiraSans(0)/m/sc/10=FiraSans:mode=node;+tlig; at 10pt not loadable: metric data not found or bad. ...etus, sit amet ultricies ipsum ultrices ut.}
line 125: Font \TU/FiraSans(0)/m/n/50=FiraSans:mode=node;+tlig; at 50pt not loadable: metric data not found or bad. \begin{cvCoverLetter}
: OpenType feature 'Numbers=Monospaced' (tnum) not(fontspec) available for font 'FiraSans' with script(fontspec) 'CustomDefault' and language 'Default'.
: OpenType feature 'Numbers=Monospaced' (tnum) not(fontspec) available for font 'FiraSans' with script(fontspec) 'CustomDefault' and language 'Default'.
line 62: Font shape `TU/FiraSans(0)/m/it' undefined(Font) using `TU/FiraSans(0)/m/n' instead
line 79: Font shape `TU/FiraSans(0)/bx/n' undefined(Font) using `TU/FiraSans(0)/m/n' instead
line 94: Font shape `TU/FiraSans(0)/m/sc' undefined(Font) using `TU/FiraSans(0)/m/n' instead
: Some font shapes were not available, defaults substituted.

**Comment by opieters** [comment]
You should add the Fira fonts in the system directory for fonts or copy them into the same folder as your .tex file.
