### ISSUE TITLE
Publish latest release to CTAN

### ISSUE THREAD

**Issue by CJCombrink** [opieters/limecv#18]
Any plans to publish the latest release (v0.1.6) to CTAN?

**Comment by fedelibre** [comment]
I'm using the `texlive-limecv` package in Fedora 31, which is still at version 0.1.3. So I hit the annoying bug [fixed here](https://github.com/opieters/limecv/commit/ff002fea2d37f6b9386a06d479d0f75ecda689ff).

Should I manually change my local file or hope for an update? ;-)

Thanks for this nice package

**Comment by opieters** [comment]
If you can hold out I'd wait. There should be an update in February :-)

**Comment by opieters** [comment]
I just submitted the latest version to CTAN. When published, I will close this issue.
