### ISSUE TITLE
Upgrade to use Fontawesome5

### ISSUE THREAD

**Issue by CJCombrink** [opieters/limecv#19]
Fontawesome5 contains some new icons, it would be nice to have access to these. 

I have tried just updating the cls file to use fontawesome5 instead of normal fontawesome but get the following issue when running:
```
Package fontawesome5 Error: The requested icon briefcase was not found. \begin{cvExperience}
```
But it does show the icon.

PS: I have almost no experience with LaTeX cls files, just tried hacking it.

**Comment by opieters** [comment]
I will try to switch to the newer Fontawesome5 later this year.

**Comment by opieters** [comment]
Should be fixed now.
