### ISSUE TITLE
Language ratings ambiguous without reference

### ISSUE THREAD

**Issue by zacmar** [opieters/limecv#22]
The language ratings are very ambiguous if only the highest rating is used. The reader then does not know how long the bar can be, since no reference is provided. This may be remedied by using a different color as the border of the bar.

**Comment by opieters** [comment]
In one of the following releases, there will be an option to remove the bars. I will also change the colours to make this more interpretable.

**Comment by opieters** [comment]
Fixed in #23. If you want to use other colouring, you should change the style of predefined TikZ styles. In this case, `progressArea` is the style.
