### ISSUE TITLE
Missed the `email` key declaration

### ISSUE THREAD

**Issue by bscadh** [opieters/limecv#27]
With the following snippet in my CV,

````latex
\begin{cvReferences}
        \cvAddReference{%
            name=John Doe,
            company=Self employed,
            position=Engineer,
            mobile phone=+0123456789,
            email=john@gmail.com}%
\end{cvReferences}
````

My code does not compile successfully. The fault is to an unknown key `email`.

When I looked at the source code of the `limecv.cls`, I discovered that there isn't a declaration for the `email` key. The same observation holds here at the source code on GitHub.

**Comment by opieters** [comment]
Currently, there is no support for an email key. I fixed this in version 0.1.11.
