### ISSUE TITLE
Possibilities to reduce the file size of the pdf?

### ISSUE THREAD

**Issue by MarcoMeter** [opieters/limecv#30]
Hi
thanks for the great template. It took me some time to understand its usage, but I was finally capable to modify it to my liking.
However, I'm running now into the issue that my final PDF's size is >10mb. My cv fits on two pages. Is there any easy way to reduce its size? Website like get-in-it limit cv upload to the size of 10mb.

**Comment by JanWaldhorn** [comment]
My three-page resume is less than 100 KB in size. Mostly (large) images are the problem. Including them in a reduced size should solve the problem. Alternatively there are various PDF compressors like PDF24
