### ISSUE TITLE
Make language ratings optional

### ISSUE THREAD

**Issue by opieters** [opieters/limecv#4]
Some people thing rating a language skill is odd. So let's make it optional.

**Comment by opieters** [comment]
Fixed in version 0.1.13.

**Comment by MarcoMeter** [comment]
Hey @opieters 
how could it be possible to remove the ratings from skill set?
I think for readers the ratings are pretty ambiguous as they don't know what these measure. (years, mastery, ...)
Additionally, I want to add like a set of 20 skills or more, where this rating takes quite much space.

Thanks for making limeCV available!
