### ISSUE TITLE
Add publications section

### ISSUE THREAD

**Issue by cbcoutinho** [opieters/limecv#5]
Hi @opieters,

Thanks for publishing this great LaTeX style out in the wild! i would like to add publications to the list of supported sections, and have a working solution/fork that I would like some help with. I basically copied the 'Experiences' section and added `fullcite` commands as `cvItems`. I don't know enough about TeX documentation to know how to fill in the .dtx file - can you give me a hand there?

Thanks in advance.

**Comment by opieters** [comment]
Hi @cbcoutinho 

Thanks for the PR!

I will have a look at your pull request, which seems to be OK, and merge it later this week. I am planning on making it much easier to define new sections, such that you don't need to alter the source code. 

However, I am only planning on shipping this feature with the next minor release, which will include improved source documentation and Travis-CI build tests. So, use your own fork for now. I will close this issue after the merge.

**Comment by opieters** [comment]
The PR has been merged, so I'll close this issue.

**Comment by JanWaldhorn** [comment]
Thank you for the possibility to implement publications. Unfortunately I get the following error messages:

`Missing } inserted. \begin{cvPublications}`
`Package tikz Error: Giving up on this path. Did you forget a semicolon?. \begin{cvPublications}`
`Extra }, or forgotten \endgroup. \begin{cvPublications}`
`\begin{tikzpicture} on input line 84 ended by \end{cvPublications}. \end{cvPublications}`

Any hint?

**Comment by opieters** [comment]
Can you post a minimal working example (MWE) to illustrate this issue?

**Comment by JanWaldhorn** [comment]
Hi @opieters , thanks for your quick reply.  I was able to narrow down the error to the language set:
with english it works fine as soon as it is changed to german (`\cvSetLanguage{german}`), the strange error messages come up.

Here a MWE

```
% !TEX TS-program = pdflatex
% !TEX encoding = UTF-8 Unicode
\documentclass[a4paper]{limecv}
% Defaults used in template design.
\usepackage[margin=\cvMargin,noheadfoot]{geometry}
\cvSetLanguage{german}% Change to English to compile successfully
%cite 
\usepackage[backend=biber]{biblatex}                                  
\addbibresource{mylib.bib}

\begin{document}
	\begin{cvSidebar}	
	\end{cvSidebar}
	\begin{cvMainContent}
		\begin{cvPublications}
		\cvItem{ \fullcite{BOA2020} };
		\cvItem{ \fullcite{Wagner2020} };
		\end{cvPublications}
	\end{cvMainContent}
\end{document}
```

Attached the zip with a bib file, but you can use anyone.
[limecv_puplication_error_german.zip](https://github.com/opieters/limecv/files/6733562/limecv_puplication_error_german.zip)

 Hope this information helps. Thanks for your work.

**Comment by opieters** [comment]
This issue is probably related to pdflatex not recognising the character `ö` in the code. I updated it to `\"{o}`. Can you try it now with the latest version on GitHub?

**Comment by JanWaldhorn** [comment]
I have just downloaded and compiled the latest version. Unfortunately, the error remains. 

If I change locally in the limecv.cls `Ver\"{o}ffentlichungen`  to `Publikationen` it works though.

`\pgfkeys{/@cv/names/publications = Ver\"{o}ffentlichungen}%`

`\pgfkeys{/@cv/names/publications = Publikationen}%`
