### ISSUE TITLE
Make it easier to define new sections

### ISSUE THREAD

**Issue by opieters** [opieters/limecv#8]
Creating new sections requires to edit the source code or to use LaTeX hacks. Additionally, it also requires knowledge of how `limecv` works internally. This should be made much easier and more accessible.

**Comment by TOmas2331** [comment]
Hi, is possible to add section Certification with same design as Education and Experience?
Thank you

**Comment by opieters** [comment]
Yes, but you will have to hack the document class to do that. I will add a more user friendly API some time in the future.

**Comment by TOmas2331** [comment]
I will try myself but which file limecv.cls or limecv.dtx?

**Comment by opieters** [comment]
When you just want to create a new section, you should modify the .cls file. This is the file latex looks at when compiling the document.

**Comment by kongyanye** [comment]
Has this function been implemented?

**Comment by TOmas2331** [comment]
Do not think so but I can send you my source code...

Dňa št, 21. feb 2019 9:46 Hanling Wang <notifications@github.com>
napísal(a):

**Comment by Pouya-Kiani** [comment]
Hi there, i'm trying to add a new environment, Certificates for example. i've added  these lines to the .cls file:
`\NewDocumentEnvironment{Certificates}{}{%`
`  \cv@Title{\pgfkeysvalueof{/@cv/names/certificates}}{\faBriefcase}`
`  \stepcounter{cv@itemPrev}`
`  \stepcounter{cv@itemNext}`
`  \cv@definecvItem`
`}{%`
`  \cv@EndSectionDraw`
`  \stepcounter{cv@lastItem}`
`  \draw (item \the\value{cv@itemPrev}.south west)`
`   node (cv@last item \the\value{cv@lastItem}) {};`
`}`
and of course defined /@cv/names/certificates variable using:
`\pgfkeys{/@cv/names/certificates = Certificates}%`
but i'm still getting an error saying the environement is not defined. Am i missing something? I'll appreciate your help. 
P.S. i'm using the xelatex file in the example.

**Comment by opieters** [comment]
Please use the new interface` \cvList`. Documentation was updated to highlight the features. It is now also used internally.

**Comment by MarcoMeter** [comment]
Could somebody provide an example for the usage of `\cvList`? Or how could an icon be overriden in my main tex file? Overriding the title works for me like this `\pgfkeys{/@cv/names/education = Teaching}`.
Got it

```
\cvList{cvCertificate}{certificate}{\faCamera}
\pgfkeys{/@cv/names/certificate = Awards and Certificates}
```

**Comment by sven1904** [comment]
Does anyone know how I can add a section without formatting.
If I use `\cvList` to define a custom section, I have to use `\cvItem{...}` inside the environment, which leads to having the "time line" on the left side (see education/experience).
Omitting `\cvItem` leads to this error message:
```
! Package pgf Error: No shape named `item 10' is known.

See the pgf package documentation for explanation.
```

And using no environment at all, e.g. just writing something like `Hello`, leads to:
```
Missing character: There is no H in font nullfont!
Missing character: There is no e in font nullfont!
Missing character: There is no l in font nullfont!
Missing character: There is no l in font nullfont!
Missing character: There is no o in font nullfont!
```
Is there any way to add unformatted text or some custom minipage without editing the source code?

**Comment by opieters** [comment]
For now, there's no option unfortunately. Feel free to open _a separate_ ticket for this issue. I'll try and address it when I have time.
